// Job-aware application form: validates locally, stores locally, then shows confirmation.
let uploadedResume = null;
const requiredFields = ['fullName', 'email', 'phone', 'college', 'degree', 'experience', 'skills', 'location', 'coverLetter'];
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
function validateApplication(form) { const values = Object.fromEntries(new FormData(form).entries()), errors = []; requiredFields.forEach((field) => { if (!String(values[field] || '').trim()) errors.push({ field, message: 'This field is required.' }); }); if (!uploadedResume) errors.push({ field: 'resume-file', message: 'Please upload your resume.' }); if (values.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)) errors.push({ field:'email',message:'Enter a valid email address.' }); if (values.phone && !/^\+?[0-9\s()-]{7,20}$/.test(values.phone)) errors.push({ field:'phone',message:'Enter a valid phone number.' }); ['portfolioUrl','linkedin','github'].forEach((field) => { if (values[field] && !/^https?:\/\//i.test(values[field])) errors.push({ field,message:'Use a full URL beginning with https://.' }); }); return { errors, values }; }
function showFieldErrors(errors) { document.querySelectorAll('.field-error').forEach((el) => el.remove()); document.querySelectorAll('.input-error').forEach((el) => el.classList.remove('input-error')); errors.forEach(({field,message}) => { const input = field === 'resume-file' ? document.getElementById('upload-zone') : document.querySelector(`[name="${field}"]`) || document.getElementById(field); if (!input) return; input.classList.add('input-error'); const error = document.createElement('small'); error.className = 'field-error'; error.textContent = message; input.insertAdjacentElement('afterend', error); }); }
function setResume(file) { if (!file) return; if (!/\.(pdf|doc|docx)$/i.test(file.name) || file.size > 8 * 1024 * 1024) return showToast('Use a PDF, DOC, or DOCX smaller than 8 MB.', 'error'); uploadedResume = file; document.getElementById('file-name').textContent = `Selected: ${file.name}`; document.getElementById('upload-progress').style.width = '100%'; }
function initUpload() { const zone = document.getElementById('upload-zone'), input = document.getElementById('resume-file'); if (!zone) return; zone.addEventListener('click', () => input.click()); zone.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') input.click(); }); input.addEventListener('change', () => setResume(input.files[0])); ['dragenter','dragover'].forEach((name) => zone.addEventListener(name, (event) => { event.preventDefault(); zone.classList.add('drag'); })); ['dragleave','drop'].forEach((name) => zone.addEventListener(name, (event) => { event.preventDefault(); zone.classList.remove('drag'); })); zone.addEventListener('drop', (event) => setResume(event.dataTransfer.files[0])); }
function showConfirmation(application, job) { const modal = document.getElementById('success-modal'); modal.querySelector('.modal-card').innerHTML = `<div class="success-badge">✓</div><h2>🎉 Congratulations!</h2><p>Your application has been submitted successfully.</p><p>Thank you for applying through CareerFlow. The recruiter will review your profile and contact you if you are shortlisted.</p><div class="application-summary"><p><strong>Applicant:</strong> ${escapeHtml(application.fullName)}</p><p><strong>Role:</strong> ${escapeHtml(job.title)}</p><p><strong>Company:</strong> ${escapeHtml(job.company)}</p><p><strong>Application ID:</strong> ${application.id}</p><p><strong>Submitted:</strong> ${new Date(application.submittedAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p></div><div class="card-actions"><a class="btn btn-secondary" href="jobs.html">Back to Jobs</a><a class="btn btn-primary" href="index.html">Go to Home</a></div>`; modal.hidden = false; }
function handleApplicationSubmit(event) { event.preventDefault(); const { errors, values } = validateApplication(event.currentTarget); showFieldErrors(errors); if (errors.length) return showToast('Please correct the highlighted fields.', 'error'); const jobId = new URLSearchParams(location.search).get('job'); const job = getStoredJobs().find((item) => item.id === jobId) || { title:'Career opportunity',company:'CareerFlow' }; const application = { id:`CF-${Date.now().toString(36).toUpperCase()}`, ...values, resumeName:uploadedResume.name, jobId, jobTitle:job.title, company:job.company, status:'Under review', submittedAt:new Date().toISOString() }; const applications = getApplications(); applications.push(application); saveApplications(applications); event.currentTarget.reset(); uploadedResume = null; document.getElementById('file-name').textContent = ''; document.getElementById('upload-progress').style.width = '0'; showConfirmation(application, job); }
function setApplicationContext() { const jobId = new URLSearchParams(location.search).get('job'); const job = getStoredJobs().find((item) => item.id === jobId); if (!job) return; const heading = document.querySelector('.form-card h1'); const copy = document.querySelector('.form-card .section-heading p'); const min = Number(job.salary?.minINR || 0), max = Number(job.salary?.maxINR || min), period = job.salary?.period || 'year'; const inr = new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}), usd = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}); const inrRange = min === max ? inr.format(min) : `${inr.format(min)}–${inr.format(max)}`; const usdRange = min === max ? usd.format(Math.round(min/85)) : `${usd.format(Math.round(min/85))}–${usd.format(Math.round(max/85))}`; if (heading) heading.textContent = `Apply for ${job.title}`; if (copy) copy.innerHTML = `${escapeHtml(job.company)} · ${escapeHtml(job.location)}<br><strong>${inrRange} per ${period}</strong> <small>(${usdRange}/${period})</small>`; }
const applicationForm = document.getElementById('application-form'); if (applicationForm) { setApplicationContext(); initUpload(); applicationForm.addEventListener('submit', handleApplicationSubmit); }
