// Job card rendering, saved jobs, company cards and sharing.
let jobs = getStoredJobs();
let savedJobs = getSavedJobs();
function refreshJobState() { jobs = getStoredJobs(); savedJobs = getSavedJobs(); }
// Shared salary formatter: INR is the source of truth, USD uses ₹85 per USD.
function formatSalary(value) { const salary = typeof value === 'number' ? { minINR:value * 85, maxINR:value * 85, period:'year' } : value; const min = Number(salary?.minINR || 0), max = Number(salary?.maxINR || min), period = salary?.period || 'year'; const inr = new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}); const usd = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}); const range = (formatter, divisor=1) => min === max ? formatter.format(Math.round(min/divisor)) : `${formatter.format(Math.round(min/divisor))}–${formatter.format(Math.round(max/divisor))}`; return { inr: `${range(inr)} per ${period}`, usd: `(${range(usd,85)}/${period})`, minINR:min, maxINR:max, period }; }
function salaryMarkup(value) { const salary = formatSalary(value); return `<div class="salary-block"><span class="salary-label">Salary</span><strong class="salary-inr">${salary.inr}</strong><span class="salary-usd">${salary.usd}</span></div>`; }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function buildJobCard(job, isSaved = false) {
  return `<article class="job-card glass-card"><div class="company-row"><div><div class="company-logo">${escapeHtml(job.logo)}</div><h3>${escapeHtml(job.title)}</h3><p>${escapeHtml(job.company)}</p></div>${salaryMarkup(job.salary)}</div><p class="description">${escapeHtml(job.description)}</p><div class="job-meta"><span>${escapeHtml(job.location)}</span><span>${escapeHtml(job.experience)}</span><span>${escapeHtml(job.type)}</span><span>${escapeHtml(job.mode)}</span></div><div class="job-tags">${(job.skills || []).slice(0,5).map((skill) => `<span>${escapeHtml(skill)}</span>`).join('')}</div><div class="job-footer"><span>Posted ${new Date(job.posted).toLocaleDateString('en-IN',{month:'short',day:'numeric'})}</span><div class="card-actions"><button class="save-btn ${isSaved?'active':''}" data-action="save" data-id="${job.id}">${isSaved?'Saved':'Save'}</button><button class="share-btn" data-action="share" data-id="${job.id}">Share</button><a class="detail-btn" href="job-details.html?id=${encodeURIComponent(job.id)}">Details</a></div></div></article>`;
}
function renderJobsList() { refreshJobState(); const root = document.getElementById('jobs-list'); if (!root) return; const filtered = getFilteredJobs(); document.getElementById('results-count').textContent = `${filtered.length.toLocaleString()} opportunities found`; root.innerHTML = filtered.length ? filtered.map((job)=>buildJobCard(job,savedJobs.includes(job.id))).join('') : '<div class="empty-state glass-card"><h3>No matching roles yet</h3><p>Try a broader skill, title, company, or location.</p></div>'; }
// Compact home-only presentation; full metadata remains on listing and details pages.
function buildHomeJobCard(job) { const salary = formatSalary(job.salary); const description = String(job.description || '').split(/\s+/).slice(0, 26).join(' '); return `<a class="home-job-card glass-card" href="job-details.html?id=${encodeURIComponent(job.id)}" aria-label="View ${escapeHtml(job.title)} at ${escapeHtml(job.company)}"><div class="home-job-heading"><div class="company-logo">${escapeHtml(job.logo)}</div><div><h3>${escapeHtml(job.title)}</h3><p>${escapeHtml(job.company)}</p></div></div><p class="home-job-description">${escapeHtml(description)}${description.length < String(job.description || '').length ? '…' : ''}</p><div class="home-job-bottom"><span class="home-job-location">${escapeHtml(job.location)}</span><div class="home-job-salary"><strong>${salary.inr}</strong><small>${salary.usd}</small></div></div><span class="btn btn-primary home-job-action">View Details</span></a>`; }
function renderFeaturedJobs() { const root = document.getElementById('featured-jobs'); if (!root) return; refreshJobState(); const latest = [...jobs].sort((a,b) => new Date(b.posted) - new Date(a.posted)).slice(0,6); root.innerHTML = latest.map(buildHomeJobCard).join(''); }
function renderCategories() { const root = document.getElementById('category-grid'); if (!root) return; const categories = [['Frontend','Frontend Development'],['Backend','Backend Development'],['Python','Python'],['AI','AI & Machine Learning'],['Internships','Internship'],['Data','Data Science'],['Cloud','DevOps & Cloud'],['Design','Design']]; root.innerHTML = categories.map(([label,query])=>`<a class="category-card glass-card" href="jobs.html?q=${encodeURIComponent(query)}"><h3>${label}</h3><p>Explore open roles →</p></a>`).join(''); }
function renderCompanyGrid() { const root = document.getElementById('company-grid'); if (!root) return; refreshJobState(); root.innerHTML = APP_DATA.companies.slice(0,10).map((company,index)=>{ const open=jobs.filter((job)=>job.company===company.name).length; const image=`assets/images1/skills/${index + 1}.jpeg`; return `<article class="company-card glass-card"><img class="company-image" src="${image}" alt="${escapeHtml(company.name)} logo" loading="lazy" decoding="async"><h3>${escapeHtml(company.name)}</h3><p>★★★★★ ${company.rating || '4.7'}</p><p>${open} open jobs</p><a class="btn btn-secondary company-link" href="company.html?name=${encodeURIComponent(company.name)}">View company</a></article>`; }).join(''); }
async function shareJob(job) { const url = `${location.origin}${location.pathname.replace(/[^/]*$/, '')}job-details.html?id=${encodeURIComponent(job.id)}`; const payload={title:`${job.title} at ${job.company}`,text:`Explore ${job.title} at ${job.company} on CareerFlow`,url}; if (navigator.share) { try { await navigator.share(payload); } catch (error) { if (error.name !== 'AbortError') showToast('Unable to open sharing options.', 'error'); } return; } const links=[['LinkedIn',`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`],['WhatsApp',`https://wa.me/?text=${encodeURIComponent(payload.text+' '+url)}`],['Email',`mailto:?subject=${encodeURIComponent(payload.title)}&body=${encodeURIComponent(payload.text+' '+url)}`],['X',`https://twitter.com/intent/tweet?text=${encodeURIComponent(payload.text)}&url=${encodeURIComponent(url)}`]]; const choice=window.prompt(`Share via:\n${links.map(([name],i)=>`${i+1}. ${name}`).join('\n')}\nEnter 1–4, or cancel to copy the link.`); const selected=links[Number(choice)-1]; if (selected) window.open(selected[1],'_blank','noopener'); else navigator.clipboard?.writeText(url).then(()=>showToast('Link copied to clipboard')); }
function handleCardActions(event) { const target=event.target.closest('[data-action]'); if (!target) return; refreshJobState(); const job=jobs.find((entry)=>entry.id===target.dataset.id); if (!job) return; if (target.dataset.action==='save') { const next=savedJobs.includes(job.id)?savedJobs.filter((id)=>id!==job.id):[...savedJobs,job.id]; saveSavedJobs(next); showToast(next.includes(job.id)?'Job saved':'Job removed','success'); renderJobsList(); renderFeaturedJobs(); } if (target.dataset.action==='share') shareJob(job); }
function setupHomePage() { renderCategories(); renderCompanyGrid(); renderFeaturedJobs(); document.getElementById('hero-search-form')?.addEventListener('submit',(event)=>{event.preventDefault(); const query=document.getElementById('hero-search-input').value.trim(); if (!query) return showToast('Enter a job title, skill, or company.'); sessionStorage.setItem('careerflow-search',query); location.href='jobs.html';}); document.getElementById('newsletter-form')?.addEventListener('submit',(event)=>{event.preventDefault(); event.currentTarget.reset();showToast('You are subscribed to job alerts.','success');}); }
function renderJobDetails() { const hero=document.getElementById('job-detail-hero'); if (!hero) return; refreshJobState(); const job=jobs.find((entry)=>entry.id===new URLSearchParams(location.search).get('id')) || jobs[0]; hero.innerHTML=`<span class="eyebrow">${escapeHtml(job.role)}</span><h1>${escapeHtml(job.title)}</h1><p>${escapeHtml(job.company)} · ${escapeHtml(job.location)}</p>${salaryMarkup(job.salary)}<a class="btn btn-primary" href="apply.html?job=${encodeURIComponent(job.id)}">Apply now</a>`; const fill=(id,items)=>{const el=document.getElementById(id);if(el)el.innerHTML=(items||[]).map((item)=>`<li>${escapeHtml(item)}</li>`).join('');}; const description=document.getElementById('job-description');if(description)description.textContent=job.description;fill('job-responsibilities',job.responsibilities);fill('job-requirements',job.requirements);fill('job-benefits',job.benefits); const company=document.getElementById('company-info');if(company)company.innerHTML=`<strong>${escapeHtml(job.company)}</strong><p>Rating 4.7 · Growing team</p>`; }
document.addEventListener('click',handleCardActions);
if (document.getElementById('jobs-list')) renderJobsList();
if (document.getElementById('featured-jobs')) setupHomePage();
if (document.getElementById('job-detail-hero')) renderJobDetails();
